# Generated by Django 3.2.9 on 2021-11-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='youtube_urk',
            field=models.URLField(null=True),
        ),
    ]
