# Generated by Django 3.2.9 on 2021-11-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_alter_idea_youtube_urk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='youtube_urk',
            field=models.URLField(blank=True, null=True),
        ),
    ]
