# Generated by Django 3.2.9 on 2021-11-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_alter_idea_youtube_urk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='youtube_urk',
            new_name='youtube_url',
        ),
    ]
